import type { Redis } from 'ioredis';
import { streamKey } from '@flower/backend';
import { discoverTenantStreams } from '../realtime-relay/relay.js';

/**
 * Realtime Stream retention (task 2.8, ADR-0017 §5). Each `rt:stream:{tenantId}`
 * is trimmed by **elapsed time** — every entry older than the retention target
 * becomes eligible for eviction — via `XTRIM … MINID`. **Never `MAXLEN`**: the
 * contract is "≈ N hours of history", never "the last N entries". A Redis
 * Stream entry auto-generated by `XADD key *` has id `<unixMillis>-<seq>`, so
 * the retention floor for "now − retention" is simply `<nowMs − retentionMs>-0`.
 *
 * The job:
 *   - is safe to run repeatedly / concurrently — `XTRIM` only ever *removes*
 *     entries strictly below the floor; running it twice in a row (or from two
 *     schedulers) just means the second call finds nothing left to remove. It
 *     never mutates an entry, so `event_id` / `seq` inside a retained envelope
 *     are untouched.
 *   - is per-tenant independent — the floor is computed from wall-clock time,
 *     identical for every tenant, and `XTRIM rt:stream:{A}` cannot touch
 *     `rt:stream:{B}`.
 *   - never touches the live Pub/Sub channels (`rt:live:*`) — only the durable
 *     Streams.
 *
 * A client whose persisted scanned cursor falls below a stream's retained floor
 * after a trim gets the existing `resync-required` path (ADR-0017 §5/§7,
 * `apps/realtime`'s `GatewayHub.resume` — `streamBounds().floor`); a cursor
 * still within the window replays normally. This module does not implement or
 * change that behaviour — it only makes the floor advance with time.
 */

export interface RetentionOptions {
  /** how far back to keep, in ms. Default ≈ 24h — configurable, never a
   *  hard-coded business constant (owner lock, task 2.8). */
  readonly retentionMs?: number;
  /** `SCAN COUNT` hint for tenant-stream discovery. */
  readonly tenantScanCount?: number;
  /** use the approximate (`~`) form of `MINID` — cheaper, may leave a few
   *  extra entries just past the floor (ADR-0017 §5). Default true. */
  readonly approximate?: boolean;
}

export const DEFAULT_RETENTION_MS = 24 * 60 * 60 * 1000;
const DEFAULTS = { tenantScanCount: 100, approximate: true };

/**
 * The Redis Stream id below which entries are eligible for trimming, for a
 * given wall-clock instant and retention window. Pure — the whole time-based
 * policy in one testable function, and the place to prove "no `MAXLEN` logic
 * exists" (this returns a `<ms>-<seq>` id, never a count).
 */
export function retentionFloorId(nowMs: number, retentionMs: number): string {
  const floorMs = Math.max(0, Math.trunc(nowMs) - Math.trunc(retentionMs));
  return `${floorMs}-0`;
}

/**
 * Trim one tenant's stream to the given floor id. Returns the number of entries
 * `XTRIM` reports it removed (`0` when nothing is old enough — the common case).
 */
export async function trimTenantStream(
  redis: Redis,
  tenantId: string,
  floorId: string,
  approximate = true,
): Promise<number> {
  const key = streamKey(tenantId);
  const removed = approximate
    ? await redis.xtrim(key, 'MINID', '~', floorId)
    : await redis.xtrim(key, 'MINID', floorId);
  return Number(removed) || 0;
}

export interface RetentionTickResult {
  readonly tenantsSeen: number;
  readonly trimmed: number;
  /** the floor id used this tick — for diagnostic logging, not a metric label. */
  readonly floorId: string;
}

/**
 * One retention sweep across every discovered `rt:stream:{tenantId}`. Discovery
 * is a plain Redis `SCAN` (`discoverTenantStreams`, shared with the relay) —
 * never a Postgres query; retention is a pure Redis-side maintenance concern.
 */
export async function retentionTick(
  redis: Redis,
  opts: RetentionOptions = {},
  now: () => number = Date.now,
): Promise<RetentionTickResult> {
  const retentionMs = opts.retentionMs ?? DEFAULT_RETENTION_MS;
  const approximate = opts.approximate ?? DEFAULTS.approximate;
  const floorId = retentionFloorId(now(), retentionMs);

  const tenantIds = await discoverTenantStreams(
    redis,
    opts.tenantScanCount ?? DEFAULTS.tenantScanCount,
  );
  let trimmed = 0;
  for (const tenantId of tenantIds) {
    trimmed += await trimTenantStream(redis, tenantId, floorId, approximate);
  }
  return { tenantsSeen: tenantIds.length, trimmed, floorId };
}
