import { randomBytes } from 'node:crypto';
import {
  canonicalizeSku,
  isValidBarcodeValue,
  QR_VALUE_RE,
  SKU_VALUE_RE,
  type IdentifierCodeType,
} from '@flower/shared-types';
import { DomainError } from '../../common/errors/domain-error.js';

/**
 * Task 3.5 identifier value handling. Pure functions + the QR generator — no DB,
 * no context. `tenant.businessTypeKey` is never consulted (HG3-NO-BT-BRANCH):
 * the only inputs are `codeType` + the raw value.
 *
 * Canonical forms (owner "SKU NORMALIZATION" / "BARCODE SEMANTICS" / "QR
 * SEMANTICS"):
 *   - SKU     — trim + locale-independent upper-case, then `SKU_VALUE_RE`. So
 *               `"abc-1"` and `"ABC-1"` are the SAME SKU.
 *   - BARCODE — trim only (never case-folded); bounded, control-char-free. No
 *               symbology parsing / checksum.
 *   - QR      — the client value is REJECTED; the server mints an opaque,
 *               cryptographically-random 40-hex-char token carrying no tenant /
 *               customer / product / price / stock / business data.
 */

/** 160 bits of entropy — a collision needs ~2^80 QRs; the `(tenantId, value)`
 *  unique index is the final backstop and the repository retries on the (never
 *  observed) clash. */
export function generateQrValue(): string {
  return randomBytes(20).toString('hex').toUpperCase();
}

export function isGeneratedQrValue(value: string): boolean {
  return QR_VALUE_RE.test(value);
}

/**
 * Resolve the canonical value to persist for a create.
 *   - `SKU` / `BARCODE`: `rawValue` is required and validated/canonicalised.
 *   - `QR`: `rawValue` MUST be absent (a client cannot choose a QR value); the
 *     caller generates the value with `generateQrValue`.
 * Throws `DomainError` (422) on a missing / malformed / disallowed value.
 */
export function canonicalIdentifierValue(
  codeType: IdentifierCodeType,
  rawValue: string | undefined,
): { generateQr: true } | { generateQr: false; value: string } {
  if (codeType === 'QR') {
    if (rawValue !== undefined && rawValue.trim() !== '') {
      throw new DomainError(
        'IDENTIFIER_QR_VALUE_NOT_ALLOWED',
        'a QR identifier value is generated by the server and cannot be supplied by the client',
        422,
        [{ field: 'value', issue: 'must be omitted for a QR identifier' }],
      );
    }
    return { generateQr: true };
  }

  const trimmed = (rawValue ?? '').trim();
  if (trimmed === '') {
    throw new DomainError(
      'IDENTIFIER_VALUE_REQUIRED',
      `a ${codeType} identifier requires a value`,
      422,
      [{ field: 'value', issue: 'required' }],
    );
  }

  if (codeType === 'SKU') {
    const value = canonicalizeSku(trimmed);
    if (!SKU_VALUE_RE.test(value)) {
      throw new DomainError(
        'IDENTIFIER_SKU_INVALID',
        'a SKU must be 1–64 characters of A–Z, 0–9, "-", "_", "." or "/" (case is normalised)',
        422,
        [{ field: 'value', issue: 'invalid SKU format' }],
      );
    }
    return { generateQr: false, value };
  }

  // BARCODE — verbatim (trimmed), never case-folded
  if (!isValidBarcodeValue(trimmed)) {
    throw new DomainError(
      'IDENTIFIER_BARCODE_INVALID',
      'a barcode value must be 1–128 characters with no surrounding whitespace or control characters',
      422,
      [{ field: 'value', issue: 'invalid barcode value' }],
    );
  }
  return { generateQr: false, value: trimmed };
}
