import { randomUUID } from 'node:crypto';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { startTestStack, type TestStack } from '@flower/testing';
import pg from 'pg';
import {
  DISCLAIMER,
  HEAVY,
  LevelStats,
  Monitor,
  deadlocks,
  digest,
  pgShmErrors,
  postgresSettings,
  writeMetrics,
  type HttpResult,
} from './load-support.js';
import { bootApp, mintTenantToken, rolePerms, type AppHandle } from './load-sale-world.js';
import { seedReferenceRows } from './load-sales-fixture.js';

/**
 * Task 3b.10 Checkpoint G — the 100 000-RECORD worlds over real HTTP (OPT-IN, "bring your own world").
 *
 * The three 100 000-record benchmark worlds (Tender Totals · Receivables · Customer Liabilities) are generated by the frozen
 * benchmark suites; this suite does not rebuild them. It attaches to a world that was restored into a disposable PostgreSQL
 * container with a 512 MB `/dev/shm` and drives the application over HTTP (real guards, sessions) at 1 / 2 / 5 / 10
 * concurrent callers, comparing every figure with the sequential baseline and checking the authorisation of the denied callers
 * mixed into the load. Local test-container observations; not production capacity.
 *
 *   G_WORLD_URL        postgres URL of the restored world                     (required — without it the suite is skipped)
 *   G_WORLD_CONTAINER  the container name (shared-memory / memory sampling)
 *   G_WORLD_KIND       tender | receivables | liabilities
 *   G_WORLD_TENANT / G_WORLD_COMPANY   the target tenant and company
 *   G_WORLD_FROM / G_WORLD_TO          the Tender window (default 2025-07-01 .. 2026-03-31, inside the 100 000 limit)
 *   G_REPS             repetitions per level (default 8)
 */
const URL = process.env['G_WORLD_URL'];
const KIND = process.env['G_WORLD_KIND'] ?? 'tender';
const CONTAINER = process.env['G_WORLD_CONTAINER'] ?? '';
const TENANT = process.env['G_WORLD_TENANT'] ?? '';
const COMPANY = process.env['G_WORLD_COMPANY'] ?? '';
const FROM = process.env['G_WORLD_FROM'] ?? '2025-07-01';
const TO = process.env['G_WORLD_TO'] ?? '2026-03-31';
const REPS = Math.max(1, Number(process.env['G_REPS'] ?? 8));
const LEVELS = [1, 2, 5, 10];

describe.skipIf(!HEAVY || !URL)(
  '100 000-record world over HTTP (task 3b.10 Checkpoint G, opt-in)',
  () => {
    let redis: TestStack;
    let h: AppHandle;
    let admin: pg.Pool;
    const metrics: Record<string, unknown> = {
      disclaimer: DISCLAIMER,
      kind: KIND,
      reps: REPS,
      container: CONTAINER,
    };
    const tok: Record<string, string> = {};
    let branches: string[] = [];
    const foreignTenant = randomUUID();

    const slug =
      KIND === 'tender'
        ? 'tender-totals'
        : KIND === 'receivables'
          ? 'receivables'
          : 'customer-liabilities';
    const query = KIND === 'tender' ? `?from=${FROM}&to=${TO}` : '?limit=50';
    const get = async (token: string | null, url: string): Promise<HttpResult> => {
      const t0 = performance.now();
      const res = await h.app.inject({
        method: 'GET',
        url: `/v1${url}`,
        headers: token ? { authorization: `Bearer ${token}` } : {},
      });
      return { status: res.statusCode, ms: performance.now() - t0, body: res.json() };
    };
    const companyUrl = `/companies/${COMPANY}/reports/${slug}${query}`;
    const branchUrl = (i: number): string =>
      `/companies/${COMPANY}/branches/${branches[i]!}/reports/${slug}${query}`;
    const tbUrl = `/companies/${COMPANY}/reports/trial-balance?from=2025-07-01&to=2026-06-30`;

    beforeAll(async () => {
      redis = await startTestStack({ services: ['redis'] });
      admin = new pg.Pool({ connectionString: URL, max: 3 });
      h = await bootApp({ pg: URL!, redis: redis.redis.url });
      const seed = new pg.Client({ connectionString: URL });
      await seed.connect();
      await seedReferenceRows(seed, [foreignTenant]);
      await seed.end();
      branches = (
        await admin.query(`SELECT id FROM branch WHERE "companyId" = $1 ORDER BY id`, [COMPANY])
      ).rows.map((r) => r.id as string);
      tok['owner'] = await mintTenantToken(h, TENANT, rolePerms('owner'));
      tok['branchOne'] = await mintTenantToken(h, TENANT, rolePerms('owner'), {
        branchScope: [branches[0]!],
      });
      tok['foreign'] = await mintTenantToken(h, foreignTenant, rolePerms('owner'));
      metrics['settings'] = CONTAINER ? await postgresSettings(admin, CONTAINER) : null;
      metrics['world'] = {
        company: COMPANY,
        branches: branches.length,
        window: KIND === 'tender' ? { FROM, TO } : null,
      };
    }, 600_000);

    afterAll(async () => {
      writeMetrics(`http-100k-${KIND}.json`, metrics);
      await admin?.end();
      await h?.close();
      await redis?.stop();
    });

    it('HTTP load at 1 / 2 / 5 / 10 concurrent callers: identical figures, expected statuses, no leakage, 0 server errors', async () => {
      interface Job {
        key: string;
        token: string;
        url: string;
        want: number;
        base: string | null;
      }
      const owner = tok['owner']!;
      const base = async (url: string): Promise<string> => {
        const r = await get(owner, url);
        expect(r.status, url).toBe(200);
        return digest(r.body);
      };
      await get(owner, companyUrl); // warm-up
      const t0 = performance.now();
      const companyBase = await base(companyUrl);
      metrics['sequentialCompanyMs'] = Math.round(performance.now() - t0);
      const jobs: Job[] = [
        { key: 'company', token: 'owner', url: companyUrl, want: 200, base: companyBase },
        ...(await Promise.all(
          branches.slice(0, 4).map(async (_b, i): Promise<Job> => ({
            key: `branch${i}`,
            token: 'owner',
            url: branchUrl(i),
            want: 200,
            base: await base(branchUrl(i)),
          })),
        )),
        {
          key: 'branch0-as-branch0-user',
          token: 'branchOne',
          url: branchUrl(0),
          want: 200,
          base: await base(branchUrl(0)),
        },
        {
          key: 'company-as-branch0-user',
          token: 'branchOne',
          url: companyUrl,
          want: 404,
          base: null,
        },
        {
          key: 'company-as-foreign-tenant',
          token: 'foreign',
          url: companyUrl,
          want: 404,
          base: null,
        },
        { key: 'trial-balance', token: 'owner', url: tbUrl, want: 200, base: await base(tbUrl) },
      ];
      const ping = () => h.db.appClient().$queryRawUnsafe('SELECT 1');
      const monitor = new Monitor({ admin, container: CONTAINER, ping });
      const dl0 = await deadlocks(admin);
      const shm0 = CONTAINER ? await pgShmErrors(CONTAINER) : 0;
      const rows: Record<string, unknown>[] = [];
      let cursor = 0;
      let stop: string | null = null;
      for (const level of LEVELS) {
        const stats = new LevelStats();
        monitor.start();
        for (let rep = 0; rep < REPS; rep++) {
          const batch = Array.from({ length: level }, () => jobs[cursor++ % jobs.length]!);
          const out = await Promise.all(
            batch.map(async (j) => ({ j, r: await get(tok[j.token]!, j.url) })),
          );
          for (const { j, r } of out) {
            stats.add(
              r.status,
              r.ms,
              r.status >= 400 ? (r.body as { error?: { code?: string } })?.error?.code : undefined,
            );
            if (r.status !== j.want) stats.wrong++;
            else if (j.base && digest(r.body) !== j.base) stats.wrong++;
            if (j.want === 404 && JSON.stringify(r.body).includes(COMPANY)) stats.isolation++;
          }
          if (monitor.tripped) break;
        }
        const m = await monitor.stop();
        rows.push({ level, reps: REPS, ...stats.summary(), resources: m });
        if (m.tripped) {
          stop = m.tripped;
          break;
        }
        expect(stats.fiveXx, `5xx at c=${level}`).toBe(0);
        expect(stats.wrong, `wrong status/figures at c=${level}`).toBe(0);
        expect(stats.isolation, `isolation faults at c=${level}`).toBe(0);
      }
      metrics['levels'] = rows;
      metrics['deadlocks'] = (await deadlocks(admin)) - dl0;
      metrics['pg53100'] = CONTAINER ? (await pgShmErrors(CONTAINER)) - shm0 : null;
      metrics['stop'] = stop;
      expect(stop).toBeNull();
      expect(metrics['deadlocks']).toBe(0);
      expect(metrics['pg53100'] ?? 0).toBe(0);
    }, 3_600_000);
  },
);
